[package]
name = "Nust"
version = "0.1.0"
authors = ["shmuelamit <shmuelamit@mail.tau.ac.il>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
